-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-03-26 11:09:35 WET
--   site:      SQL Server 2008
--   type:      SQL Server 2008



CREATE TABLE Dim_Customer 
    (
     Customer_SKEY INTEGER NOT NULL , 
     CustomerID NCHAR (5) , 
     CompanyName NVARCHAR (40) , 
     ContactName NVARCHAR (30) , 
     ContactTitle NVARCHAR (30) , 
     Age SMALLINT NOT NULL , 
     Address NVARCHAR (60) , 
     City NVARCHAR (15) , 
     Region NVARCHAR (15) , 
     PostalCode NVARCHAR (10) , 
     Country NVARCHAR (15) , 
     Phone NVARCHAR (24) , 
     Fax NVARCHAR (24) , 
     CustomerSegmentID SMALLINT , 
     CustomerSegment VARCHAR (20) , 
     CustomerType NVARCHAR (20) 
    )
GO

ALTER TABLE Dim_Customer ADD CONSTRAINT Dim_Customer_PKv1 PRIMARY KEY CLUSTERED (Customer_SKEY)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Dim_Date 
    (
     Date_SKEY INTEGER NOT NULL , 
     Date DATE NOT NULL , 
     Month INTEGER , 
     MonthName VARCHAR (15) , 
     Quarter INTEGER , 
     Semester INTEGER , 
     Year INTEGER , 
     IsHoliday BIT , 
     DayName VARCHAR (15) , 
     WeekOfYear INTEGER 
    )
GO

ALTER TABLE Dim_Date ADD CONSTRAINT Dim_Date_PKv1 PRIMARY KEY CLUSTERED (Date_SKEY)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE Dim_Date ADD CONSTRAINT Dim_Date_PK UNIQUE NONCLUSTERED (Date_SKEY)
GO

CREATE TABLE Dim_Product 
    (
     Product_SKEY INTEGER NOT NULL , 
     ProductID INTEGER NOT NULL , 
     ProductName NVARCHAR (40) NOT NULL , 
     CategoryID INTEGER NOT NULL , 
     CategoryName NVARCHAR (15) NOT NULL , 
     CategoryDescription NTEXT , 
     QuantityPerUnit NVARCHAR (20) , 
     UnitPrice MONEY NOT NULL , 
     UnitCostPrice MONEY , 
     OriginCountry NVARCHAR (15) , 
     BiologicalLabel NVARCHAR (20) , 
     Discontinued BIT NOT NULL , 
     ManufacturerID INTEGER NOT NULL , 
     ManufacturerName NVARCHAR (40) 
    )
GO

ALTER TABLE Dim_Product ADD CONSTRAINT Dim_Product_PKv1 PRIMARY KEY CLUSTERED (Product_SKEY)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE Dim_Product ADD CONSTRAINT Dim_Product_PK UNIQUE NONCLUSTERED (Product_SKEY)
GO

CREATE TABLE Dim_Promotion 
    (
     Promotion_SKEY INTEGER NOT NULL , 
     SpecialOfferID INTEGER NOT NULL , 
     Description NVARCHAR (255) NOT NULL , 
     DiscountPct SMALLMONEY NOT NULL , 
     Type NVARCHAR (50) NOT NULL , 
     Category NVARCHAR (50) NOT NULL , 
     StartDate DATETIME NOT NULL , 
     EndDate DATETIME NOT NULL , 
     MinQty INTEGER NOT NULL , 
     MaxQty INTEGER 
    )
GO

ALTER TABLE Dim_Promotion ADD CONSTRAINT Dim_Promotion_PKv1 PRIMARY KEY CLUSTERED (Promotion_SKEY)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Dim_Store 
    (
     Store_SKEY INTEGER NOT NULL , 
     StoreID INTEGER NOT NULL , 
     StoreName VARCHAR (50) NOT NULL , 
     TerritoryID NVARCHAR (20) NOT NULL , 
     TerritoryDescription NCHAR (50) NOT NULL , 
     RegionID INTEGER NOT NULL , 
     RegionDescription NCHAR (50) NOT NULL , 
     City NVARCHAR (15) , 
     Country NVARCHAR (15) , 
     SalesChannel VARCHAR (10) 
    )
GO

ALTER TABLE Dim_Store ADD CONSTRAINT Dim_Store_PKv1 PRIMARY KEY CLUSTERED (Store_SKEY)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE Dim_Store ADD CONSTRAINT Dim_Store_PK UNIQUE NONCLUSTERED (Store_SKEY)
GO

CREATE TABLE Fact_Inventory 
    (
     InventoryKey INTEGER NOT NULL , 
     UnitsInStock SMALLINT NOT NULL , 
     UnitsOnOrder SMALLINT NOT NULL , 
     ReorderLevel SMALLINT , 
     StockTurnoverRate REAL , 
     DaysInStock INTEGER , 
     create_Datetime DATETIME , 
     change_datetime DATETIME , 
     delete_datetime DATETIME , 
     record_id NUMERIC (10) , 
     Dim_Product_Product_SKEY INTEGER NOT NULL , 
     Dim_Store_Store_SKEY INTEGER NOT NULL , 
     Dim_Date_Date_SKEY INTEGER NOT NULL 
    )
GO

ALTER TABLE Fact_Inventory ADD CONSTRAINT Fact_Inventory_PK PRIMARY KEY CLUSTERED (InventoryKey)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO

CREATE TABLE Fact_Sales 
    (
     Fact_Sales_ID NUMERIC (28) NOT NULL IDENTITY NOT FOR REPLICATION , 
     SalesKey INTEGER NOT NULL , 
     OrderID INTEGER NOT NULL , 
     Quantity SMALLINT , 
     UnitPrice MONEY NOT NULL , 
     UnitCostPrice MONEY , 
     Discount REAL , 
     TotalAmmount MONEY NOT NULL , 
     TotalCost MONEY NOT NULL , 
     Profit MONEY NOT NULL , 
     ShippingCost MONEY , 
     OrderDate DATETIME NOT NULL , 
     RequiredDate DATETIME , 
     DeliveryTime INTEGER , 
     create_Datetime DATETIME , 
     change_datetime DATETIME , 
     delete_datetime DATETIME , 
     record_id NUMERIC (10) , 
     Dim_Product_Product_SKEY INTEGER NOT NULL , 
     Dim_Date_Date_SKEY INTEGER NOT NULL , 
     Dim_Store_Store_SKEY INTEGER NOT NULL , 
     Dim_Customer_Customer_SKEY INTEGER NOT NULL , 
     Dim_Promotion_Promotion_SKEY INTEGER 
    )
GO

ALTER TABLE Fact_Sales ADD CONSTRAINT Fact_Sales_PKv1 PRIMARY KEY CLUSTERED (SalesKey)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
GO
ALTER TABLE Fact_Sales ADD CONSTRAINT Fact_Sales_PK UNIQUE NONCLUSTERED (Fact_Sales_ID)
GO

ALTER TABLE Fact_Inventory 
    ADD CONSTRAINT Fact_Inventory_Dim_Date_FK FOREIGN KEY 
    ( 
     Dim_Date_Date_SKEY
    ) 
    REFERENCES Dim_Date 
    ( 
     Date_SKEY 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Inventory 
    ADD CONSTRAINT Fact_Inventory_Dim_Product_FK FOREIGN KEY 
    ( 
     Dim_Product_Product_SKEY
    ) 
    REFERENCES Dim_Product 
    ( 
     Product_SKEY 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Inventory 
    ADD CONSTRAINT Fact_Inventory_Dim_Store_FK FOREIGN KEY 
    ( 
     Dim_Store_Store_SKEY
    ) 
    REFERENCES Dim_Store 
    ( 
     Store_SKEY 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Customer_FK FOREIGN KEY 
    ( 
     Dim_Customer_Customer_SKEY
    ) 
    REFERENCES Dim_Customer 
    ( 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Date_FK FOREIGN KEY 
    ( 
     Dim_Date_Date_SKEY
    ) 
    REFERENCES Dim_Date 
    ( 
     Date_SKEY 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Product_FK FOREIGN KEY 
    ( 
     Dim_Product_Product_SKEY
    ) 
    REFERENCES Dim_Product 
    ( 
     Product_SKEY 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Promotion_FK FOREIGN KEY 
    ( 
     Dim_Promotion_Promotion_SKEY
    ) 
    REFERENCES Dim_Promotion 
    ( 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO

ALTER TABLE Fact_Sales 
    ADD CONSTRAINT Fact_Sales_Dim_Store_FK FOREIGN KEY 
    ( 
     Dim_Store_Store_SKEY
    ) 
    REFERENCES Dim_Store 
    ( 
     Store_SKEY 
    ) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION 
GO



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
